[project]
name = "atom"
version = "0.1.0"
description = ""
authors = [
    {name = "chetianjian",email = "tc3149@columbia.edu"}
]
readme = "README.md"
requires-python = "3.11.5"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
